# Scheduled job that checks for new Hearthstone cards and downloads/commit them to the repo

name: Update Card Images

on:
  schedule:
    - cron: '0 0 1 * *'  # 1st day of every month at 00:00 UTC

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: node ./update_card_images.js
    - name: Add & Commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update data"
        git push
