# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'  # Friday midnight

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: node ./update_card_images.js
    - name: Add & Commit
      # You may pin to the exact commit or the version.
      uses: EndBug/add-and-commit@57c075ed5f8e31ea885906eaa0891f28131ae4dc
      with:
        author_name: Oliver Fei
        author_email: ofei006@uottawa.ca
        message: Update Card Images
        push: true
      env:
        # This is necessary in order to push a commit to the repo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
